#Steps to use docker:
#	Install docker
#	Install plugins for docker in vscode
#	(if remote): set docker context: https://www.docker.com/blog/how-to-deploy-on-remote-docker-hosts-with-docker-compose/
#	(if remote): set ssh-agent: https://code.visualstudio.com/docs/containers/ssh#_set-up-ssh-tunneling
#	Run docker build in the correct context for an exmaple execution. Substitute the data and parameters with the desired inputs. 
FROM mathworks/matlab:r2021a

ARG MLM_LICENSE_FILE
RUN export CC="gcc"
RUN export CXX="g++"
COPY . /cpp/src
WORKDIR /cpp/src
RUN sudo apt-get update
RUN sudo apt-get install -y \
	cmake \
	g++ \
	gcc \
	libboost-all-dev \
	libeigen3-dev \
	libtbb-dev \
	ninja-build
RUN sudo cmake -G Ninja
RUN sudo ninja
#RUN sudo cp ../HH_init_cond.mat ./
RUN sudo ./cmake_HH_example -h
RUN sudo ./cmake_HH_example --silence